[package]
name = "dog-auth-local"
version = "0.2.0"
edition = "2021"
description = "Local (username/password) authentication strategy for DogRS"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Jitpomi/dogrs"
documentation = "https://docs.rs/dog-auth-local"
readme = "README.md"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bcrypt = "0.19.1"
dog-auth = { path = "../dog-auth", version = "0.2.0" }
dog-core = { path = "../dog-core", version = "0.2.0" }
serde_json = "1.0"
tokio = { version = "1", features = ["rt", "sync"] }

[dev-dependencies]
tokio = { version = "1.52", features = ["full"] }
